<?php foreach($this->getFeaturedProducts() as $_product): ?>
<form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form">
<a href="<?php echo $_product->getProductUrl() ?>">
<?php echo $this->htmlEscape($_product->getName()) ?></a>
<img class="product-image" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200, 200) ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
<?php if($_product->isSaleable()): ?>
<button class="form-button" onclick="setLocation
('<?php echo $this->getAddToCartUrl($_product) ?>')">
<span><?php echo $this->__('Add to Cart') ?></span></button>
<?php else: ?>
<div class="out-of-stock"><?php echo
$this->__('Out of stock') ?></div>
<?php endif; ?>
</form>
<?php endforeach; ?>